name: Publish (Canary)

on:
  workflow_dispatch:
    inputs:
      prId:
        description: PR id
        required: true
        type: string

jobs:
  run-check-workflow:
    uses: ./.github/workflows/checks.yml
  publish-canary:
    if: inputs.prId
    runs-on: ubuntu-latest
    needs: run-check-workflow
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Change Node.js Version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.16.0
      - name: Cache node_modules
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm run build
      - run: |
          git fetch --quiet --tags --unshallow
          npm run release:canary -- --pr ${{ inputs.prId }} --target comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
