name: Publish (Release)

on:
  push:
    branches:
      - main
      - next

jobs:
  publish-release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
        with:
          filterOutClosed: true
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Change Node.js Version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.16.0
      - name: Cache node_modules
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: |
          git fetch --tags --unshallow
          npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PR: ${{ steps.PR.outputs.number }}
